arctern-io/arctern

core/src/CMakeLists.txt, core/src/gis/cpp/geometry/geometry.cpp, core/src/gis/cpp/geometry/geometry.h, core/unittest/gis/cpp/geometry_test.cpp, python/cython/gis.h, python/cython/zilliz_gis_core.pyx, python/cython/zilliz_gis_core_.pxd, python/test/geo/geo_tests.py
add python wrapper for ST_point
provide python interface for users
Yes, add python wrapper for ST_point
add unittest
=> Add python wrapper for ST_point

gis_with_conda.md
What changes were proposed in this pull request?
Format the content
Rewrite some contents
Why are the changes needed?
Optimize the content of this document
Does this PR introduce any user-facing change?
No.
How was this patch tested?
Not required
=> modify gis_with_conda.md

docker/build_env/Dockerfile, docker/build_env/docker-entrypoint.sh, docker/build_env/zgis.yml
feature
What this PR does / why we need it:
Add build environment Dockerfile
Fixes #36
=> Add build environment Dockerfile

doc/code-structure.md, doc/compile-with-conda.md, doc/extra/build-spark-environment.md
What changes were proposed in this pull request?
add doc directory and some documents, the content of these documents needs to be improved in the future.
Does this PR introduce any user-facing change?
No.
How was this patch tested?
Not required
=> add document list

cpp/src/gis/cpu/gdal_impl.cpp, cpp/unittest/gis/cpp/geometry_test.cpp
1. add 1 unittest with invalid wkt input
2. bug fixed
=> fix #45 ST_IsValid crashed if input is not valid geometry

ci/jenkins/Jenkinsfile, ci/jenkins/pod/gis-cpu-version-ubuntu16.04-build-env-pod.yaml, ci/jenkins/pod/gis-gpu-version-ubuntu16.04-build-env-pod.yaml
Add Jenkins CI for GIS
feature
Fixes #48
=> Add Jenkins CI for GIS

cpp/src/gis/cpu/gdal_based_impl.cpp
=> change build target

python/zilliz_gis/cython/gis.h, python/zilliz_gis/cython/zilliz_gis_core_.pyx, python/zilliz_gis/cython/zilliz_gis_core__.pxd
=> remove unused code

cpp/CMakeLists.txt
What changes were proposed in this pull request?
add the following complie-time check info to cpp/CMakelists.txt：
- build time
- branch
- last commit id
Does this PR introduce any user-facing change?
No.
How was this patch tested?
Not required
=> add build-time/branch/commit-id/ tips in cpp/CMakelists.txt

.clang-format, .clang-tidy, .clang-tidy-ignore, ci/jenkins/pod/gis-cpu-version-ubuntu16.04-build-env-pod.yaml, ci/jenkins/pod/gis-gpu-version-ubuntu16.04-build-env-pod.yaml, ci/scripts/cpp_build.sh, cpp/CMakeLists.txt, cpp/build-support/cpplint.py, cpp/build-support/lint_exclusions.txt, cpp/build-support/lintutils.py, cpp/build-support/run_clang_format.py, cpp/build-support/run_clang_tidy.py, cpp/build-support/run_cpplint.py, cpp/cmake/FindClangTools.cmake, docker/build_env/cpu/Dockerfile, docker/build_env/gpu/Dockerfile
Add Cpplint & Clang-format & Clang-tidy for GIS
feature
Fixes #59
=> Add Cpplint & Clang-format & Clang-tidy for GIS

.gitignore, cpp/CMakeLists.txt, cpp/src/common/version.h.in, cpp/src/gis/api.h, cpp/src/gis/cpu/gdal_based_impl.cpp
The changes are as follow：
- add cpp/src/common/version.h.in
- modify cpp/CMakeList.txt for automatic cpp/src/common/version.h generation
- Impl GIS_Version in cpp/src/gis/cpp/gdal_based_impl.cpp
=> Add/impl c++ function: GIS_Version

.pylintrc, ci/scripts/run_pylint.sh, cpp/build-support/cpplint.py, cpp/build-support/run_cpplint.py, docker/build_env/cpu/zgis.yml, docker/build_env/gpu/zgis.yml, zgis.yml
Add pylint for GIS
feature
Fixes #64
=> Add pylint for GIS

LICENSE
LICENSE: Apache License Version 2.0
=> add LICENSE file to root

cpp/build-support/run_cpplint.py
Cpplint attent copyright information
feature
Fixes #77
=> Cpplint attent copyright information

docker/build_env/cpu/zgis.yml, docker/build_env/gpu/Dockerfile, docker/build_env/gpu/zgis.yml
Change gpu version base docker image
feature
Fixes #84
=> Change gpu version base docker image

cpp/src/common/error.h, cpp/src/common/version.h.in, cpp/src/utils/check_status.h
file list:
cpp/src/common/error.h
cpp/src/common/version.h.in
cpp/src/utils/check_status.h
=> modify for cpplint

cpp/src/gis/api.h, cpp/src/render/2d/choropleth_map/choropleth_map.cpp
file list:
cpp/src/gis/api.h
cpp/src/render/2d/choropleth_map/choropleth_map.cpp
=> clang-format two files

ci/jenkins/step/build.groovy, ci/scripts/cpp_build.sh, ci/scripts/run_pylint.sh, docker/spark/cpu/Dockerfile, docker/spark/gpu/Dockerfile
feature
What this PR does / why we need it:
Open check cpplint & clang-format & pylint operation
Fixes #120
=> Open check cpplint & clang-format & pylint operation

cpp/src/gis/api.h, cpp/src/gis/gdal/gis_functions.cpp, cpp/src/gis/gdal/gis_functions.h, cpp/src/gis/gis_functions.cpp, cpp/unittest/gis/gis_functions_tests.cpp, python/tests/geo/geo_test.py, python/zilliz_gis/cython/gis.h, python/zilliz_gis/cython/zilliz_gis_core_.pyx, python/zilliz_gis/cython/zilliz_gis_core__.pxd, spark/pyspark/examples/gis/spark_udf_ex.py, spark/pyspark/zilliz_pyspark/_wrapper_func.py
add `ST_GeomFromGeoJSON`, includes cpp, cpp unittest, python wrapper, python unittest, pandas_uf, spark test
=> add ST_GeomFromGeoJSON

spark/pyspark/examples/gis/spark_udf_ex.py, spark/pyspark/zilliz_pyspark/_wrapper_func.py
create geometry from text, includes:
- `ST_PointFromText_UDF` 
- `ST_PolygonFromText_UDF`
- `ST_LineStringFromText_UDF`
- `ST_GeomFromText_UDF`
- `ST_GeomFromWKT_UDF`
=> create geometry from text

cpp/src/gis/api.h, cpp/src/gis/gdal/arctern_geos.h, cpp/src/gis/gdal/gis_functions.cpp, cpp/src/gis/gdal/gis_functions.h, cpp/src/gis/gis_functions.cpp, cpp/unittest/gis/gis_functions_tests.cpp, python/tests/geo/geo_test.py, python/zilliz_gis/cython/gis.h, python/zilliz_gis/cython/zilliz_gis_core_.pyx, python/zilliz_gis/cython/zilliz_gis_core__.pxd, spark/pyspark/examples/gis/spark_udf_ex.py, spark/pyspark/zilliz_pyspark/_wrapper_func.py
add ST_HausdorffDistance, includes cpp, cpp unittest, python wrapper, python unitest, spark udf, spark example
add `arctern_geos.h` for geos library.
=> add ST_HausdorffDistance

ci/jenkins/pod/arctern-cpu-version-ubuntu18.04-build-env-pod.yaml, ci/jenkins/pod/arctern-gpu-version-ubuntu18.04-build-env-pod.yaml
performance
Add pod tolerations to Jenkins slave pods
Fixes #153
=> Add pod tolerations to Jenkins slave pods

cpp/src/gis/gdal/gis_functions.cpp, cpp/unittest/gis/gis_functions_tests.cpp, spark/pyspark/examples/gis/spark_udf_ex.py
like postgis, A Equals B means  A within B and B within A.
https://postgis.net/docs/ST_Equals.html
=> fix #144, ST_Equals

cpp/src/gis/gdal/gis_functions.cpp, cpp/unittest/gis/gis_functions_tests.cpp
1. rewrite ST_Union_Aggr, calls `UnionCascaded` if the input type is `MultiPolygon`
2. speed up wkbMultiPolygon
3. add unittest
=> fix #152 ST_Union_Aggr

.env
Signed-off-by: ZhifengZhang-CN <zhifeng.zhang@zilliz.com>
bug
Fixes #141 
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
**Additional documentation (e.g. design docs, usage docs, etc.):**
=> Update .env file

doc/How-to-determine-if-tow-geometries-are-approximately-equal2.md
Add a document using shapely to determine the approximate equality of two geometry methods.
=> shapely doc

.env, doc/Build-Conda-Package.md, doc/compile-with-conda.md, docker/build_env/cpu/Dockerfile
Signed-off-by: ZhifengZhang-CN <zhifeng.zhang@zilliz.com>
document
Update build conda package document
Fixes #163 
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
**Additional documentation (e.g. design docs, usage docs, etc.):**
=> Update build conda package document

cpp/src/CMakeLists.txt, cpp/src/gis/gdal/format_conversion.cpp, cpp/src/gis/gdal/format_conversion.h, cpp/unittest/gis/gdal/CMakeLists.txt, cpp/unittest/gis/gdal/format_conversion_tests.cpp, cpp/unittest/gis/gdal/geometry_cases.h, cpp/unittest/gis/gdal/type_scan_tests.cpp
1. add gdal based wkt-wkb format conversion
2. refactor gdal unittests
=> add gdal based wkt-wkb format conversion

cpp/src/gis/api.h, cpp/src/gis/gdal/gis_functions.cpp, cpp/src/gis/gdal/gis_functions.h, cpp/src/gis/gis_functions.cpp, cpp/unittest/gis/gis_functions_tests.cpp, python/tests/geo/geo_test.py, python/zilliz_gis/cython/gis.h, python/zilliz_gis/cython/zilliz_gis_core_.pyx, python/zilliz_gis/cython/zilliz_gis_core__.pxd, spark/pyspark/examples/gis/spark_udf_ex.py, spark/pyspark/zilliz_pyspark/_wrapper_func.py
add st_curvetoline includes:
- cpp
- cpp unittest
- python wrapper
- pytest
- spark udf wrapper
- spark udf test
=> add st_curvetoline

tests/compare.py
Add curve/surface equality check cases for compare.py.
=> add curve/surface equality check cases

ci/jenkins/Jenkinsfile, ci/jenkins/step/build.groovy, ci/jenkins/step/coverage.groovy, ci/scripts/coverage.sh, ci/scripts/cpp_build.sh, codecov.yaml
feature
Add Code coverage in Jenkins CI
Fixes #248
=> Add Code coverage in Jenkins CI

.github/workflows/python.yml, ci/jenkins/Jenkinsfile
feature
Remove arctern cpu version unittest in Jenkins CI
Fixes #260
=> Remove arctern cpu version unittest in Jenkins CI

tests/compare.py
relative comparison for curve/surface
=> relative comparison for curve/surface

ci/jenkins/pod/arctern-cpu-version-ubuntu18.04-build-env-pod.yaml, ci/jenkins/pod/arctern-gpu-version-ubuntu18.04-build-env-pod.yaml, ci/jenkins/step/build.groovy, ci/scripts/check_ccache.sh, ci/scripts/cpp_build.sh, ci/scripts/update_ccache.sh, cpp/CMakeLists.txt, cpp/cmake/DefineOptions.cmake
Signed-off-by: ZhifengZhang <zhifeng.zhang@zilliz.com>
feature
Add ccache in Jenkins CI
Fixes #305 
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
**Additional documentation (e.g. design docs, usage docs, etc.):**
=> Add ccache in Jenkins CI

python/arctern/cython/arctern_core__.pxd
When there is exception in c++ code, this feature can catch the exception in c++ to exception in python.
=> support exception threw by c++

doc/compile-with-conda.md
=> fix st_transform crash bug in hadoop mode

spark/pyspark/arctern_pyspark/__init__.py, spark/pyspark/arctern_pyspark/gis_func.py
supply union_aggr and envelop_aggr functions which implemented by map_iter pandas udf.
=> Agg map iter

gui/server/manage.py, gui/server/requirements.txt
modify:
requirements.txt
manage.py
=> gui/server: add http CORS

cpp/src/render/2d/choropleth_map/choropleth_map.cpp, python/arctern/_wrapper_func.py, python/arctern/cython/arctern_core_.pyx, python/tests/geo/render_test.py, spark/pyspark/arctern_pyspark/render_func.py, spark/pyspark/examples/render/nyc_taxi.py
1. wrapper python and spark api.
2. add nyc taxi test
3. fix #356
=> weighted pointmap, done

spark/pyspark/arctern_pyspark/render_func.py
=> fix image upside down error

cpp/src/render/2d/scatter_plot/weighted_pointmap.cpp, cpp/src/render/2d/scatter_plot/weighted_pointmap.h
=> Fix storke width ruler is not enable

gui/server/README.md, gui/server/app/common/spark.py
modify files:
gui/server/app/common/spark.py
gui/server/README.md
=> move spark config params to data json config file

spark/pyspark/arctern_pyspark/render_func.py
=> use flexible schema to fix GeoHeatMap failed issue

gui/server/README.md, gui/server/app/common/spark.py
modify files:
gui/server/app/common/spark.py
=> adjust spark config set

doc/spark-on-yarn.md
=> [skip ci] add some executor config for spark-submit

tests/perf_regression.py
add performance regression script
=> add performance regression script

spark/pyspark/arctern_pyspark/gis_func.py
Since arcter python api return type is pandas.Series with binary data type, we should update udf functions in spark/pyspark/arctern_pyspark/gis_func.py
=> fix arctern_pyspark gis function for agg map iter

ci/scripts/conda/cpu/build.sh, ci/scripts/conda/gpu/build.sh
=> Get latest tag and number of commits since tag

cpp/src/gis/gdal/gis_functions.cpp, python/tests/geo/geo_test.py
=> fix ST_PolygonFromEnvelope bug

ci/scripts/run_spark_regression.sh, python/tests/geo/geo_test.py, tests/test_vectory_impl.py
the modification is consistent with PR#555
=> test vectory implementation in regression

tests/perf_regression.py
Add normalization feature for performance regression test.
=> Performance regression

.github/workflows/conda_build.yml, conda/recipes/arctern-spark/meta.yaml, conda/recipes/arctern/meta.yaml, conda/recipes/libarctern/cpu/meta.yaml, conda/recipes/libarctern/gpu/meta.yaml
=> replace conda version for PEP-386 verlib conventions

python/arctern/_wrapper_func.py, spark/pyspark/arctern_pyspark/_wrapper_func.py
=> Fix gis function definition

ci/jenkins/step/buildArcternFlaskImage.groovy, ci/jenkins/step/buildArcternSparkImage.groovy
Fix docker login failed in Jenkins CI 
Fixed #604
=> Fix docker login failed

ci/jenkins/pod/arctern-cpu-version-centos7-build-env-pod.yaml, ci/jenkins/pod/arctern-cpu-version-ubuntu18.04-build-env-pod.yaml, ci/jenkins/pod/arctern-gpu-version-centos7-build-env-pod.yaml, ci/jenkins/pod/arctern-gpu-version-ubuntu18.04-build-env-pod.yaml, ci/yaml/conda_env_python.yml, docker/build_env/build_conda_env.yml
=> Update build environment version to v0.1.1

python/arctern/_wrapper_func.py, spark/pyspark/arctern_pyspark/_wrapper_func.py
=> Fix comment error in gis comment

python/arctern/_wrapper_func.py, spark/pyspark/arctern_pyspark/_wrapper_func.py
=> Fix comment error in gis function

conda/recipes/arctern-webserver/meta.yaml
=> Fix Arctern web server conda recipes bug

cpp/src/render/utils/image/image_loader.cpp, cpp/src/render/window/window_osmesa/window_cpu_2d.cpp, python/arctern/_plot_with_map.py, python/tests/geo/plot_with_map_test.py
1. enable plot_fishnetmap
2. fix some include headers
=> add plot_fishnetmap

cpp/src/render/utils/render_utils.cpp, python/arctern/_plot_with_map.py, python/arctern/geoseries/geoarray.py, python/arctern/geoseries/geoseries.py, python/tests/geoseries/geoseries_test.py
* fix set item with NA value
* improve geo_equals
=> fix bug in GeoSeries set item with na value (#641)

python/arctern/geoseries/geoarray.py, python/arctern/geoseries/geoseries.py, python/tests/geoseries/geo_funcions_test.py, python/tests/geoseries/geoseries_test.py
=> Fix geoseries astype bytes or string

cpp/src/map_match/map_match.cpp, cpp/src/map_match/map_match.h, cpp/unittest/map_match/map_match_test.cpp, python/arctern/_wrapper_func.py, python/tests/geo/geo_test.py
1. rename sjoin to within_which
2. fix output when input series is labeled
=> rename sjoin to within_which

cpp/src/map_match/map_match.cpp, cpp/src/render/utils/render_utils.cpp, cpp/unittest/map_match/map_match_test.cpp
=> Fix Segment fault in map matching.

cpp/src/index/index_builder.cpp, cpp/unittest/gis/spatial_join/indexed_with_test.cpp
=> fix #685 index error in index_builder

.github/workflows/release.yml
=> Upload Arctern conda package when github event is release

python/arctern/plot/_plot_with_map.py
turn off axis due to confusing 3857 values
=> turn off axis

python/arctern/plot/_plot.py
=> [skip ci] modify plot_geometry comments

python/arctern/geoseries/geoseries.py
=> from branch 0.2.x
